#!/bin/bash

if [ -d /data/etc ] && [ -d /data/var/lib ] && [ -d /data/var/log ] && [ -d /data/var/spool ] ; then
    echo "Upgrading from Kolab 3.4 docker image has started!"

        mv /data/etc/{*,.*} /config/
        mv /data/var/log/{*,.*} /log/
        mv /data/var/spool/{*,.*} /spool/
        mv /data/var/lib/{*,.*} /data/

        rmdir /data/etc /data/var/log /data/var/spool /data/var/lib /data/var

        source '/lib/start/functions.sh'

        chk_env MYSQL_ROUNDCUBE_PASS
        chk_env MYSQL_ROOT_PASS
        
        /lib/start/setup-kolab.exp guam | exit 2
        /lib/start/setup-kolab.exp manticore | exit 2
        /lib/start/setup-kolab.exp roundcube | exit 2
        /lib/start/setup-kolab.exp imap | exit 2
        
        image_services_stop

    echo "Finished!"
else
    >&2 echo "Kolab 3.4 docker image directories is not detected!"
    exit 2
fi
